### ISSUE TITLE
Add an alternative backend to Berkley DB

### ISSUE THREAD

**Issue by pkubatrh** [libzhuyin/libzhuyin#10]
Given that a lot of Linux distributions are trying to get rid of BDB in the long run because of the change in license in version 6, it would be nice to provide another option to use as a backend for this project (LMDB?).

**Comment by epico** [comment]
We will consider Kyoto Cabinet, as libpinyin already used it.

**Comment by epico** [comment]
This project has been merged into libpinyin and ibus-libzhuyin.
Please try libpinyin and ibus-libzhuyin instead, thanks!
