### ISSUE TITLE
bigram is not reproducible

### ISSUE THREAD

**Issue by czchen** [libzhuyin/libzhuyin#7]
Currently Debian is working on [reproducible builds](https://wiki.debian.org/ReproducibleBuilds), but the bigram.db in libzhuyin is not [reproducible](https://reproducible.debian.net/rb-pkg/libzhuyin.html). Is it possible to modify so that libzhuyin can be reproducible?

**Comment by epico** [comment]
I think libzhuyin may not use not reproducible code, but I might be wrong.
I suspect it is caused by Berkeley DB, is other Berkeley DB data reproducible?

**Comment by epico** [comment]
This project has been merged into libpinyin and ibus-libzhuyin.
Please try libpinyin and ibus-libzhuyin instead, thanks!
